### ISSUE TITLE
Not so much an issue as a question

### ISSUE THREAD

**Issue by SuckyNoob** [Lohan120/GodotIsoPathfinder#1]
Just a quick question. I was playing around with this. Is there any way to make it so there is diagonal movement/pathfinding allowed everywhere EXCEPT corners of walls or non walkables? Thanks for your time if you answer this.

**Comment by rvcalisto** [comment]
Yes, the trick is defining what is a corner in the game space to automate it. Here's one solution, I hope this is sorta of what you had in mind.

Assuming you activated the diagonal movement, just overwrite the line 165 to 168 of the pathfinder.gd with the code below:


	#skip if cell is blocked
	if grid.has(neighbor):
			
		#skip condition
		var skip_tile = false 
		#check how many non diagonal neighbours the origin tile has
		var i = 0; for neigh in [up, down, left, right]:
			var g = neigh * next + pos
			if grid.has(g): i += 1 if grid[g][0] == "empty" else 0
			
		if i < 4: #if origin tile is possibly a corner
			for neigh in [w,a,s,d]: #check if movement is diagonal
				if !skip_tile && neighbor == neigh * next + pos:
					skip_tile = true 
			
			
		if grid[neighbor][0] == "empty" && !skip_tile:
			neighbors.append(neighbor)

This handles tiles with less than 4 non diagonal neighbors as a possible corner, and then just skips whatever adjacent diagonal movement from it.

**Comment by SuckyNoob** [comment]
Thanks man, works like a charm that's exactly what I was looking for. I found another tutorial it was in XNA though wasnt sure how to do it in gdscript. Thanks a lot. So to follow the path do I just replace the "teleport" code? Or I guess add an instance of the pathfinder to each AI entity and the Player and add the code to iterate through the path and follow it? Thanks again!

Also I noticed on one of the posts I found your demo through you said you couldnt get it to sort properly. In order to sort you need to have the Wall tiles be separate objects from the map itself, with their own collision or somehow integrated into the pathfinder as separate objects, then along with the player add those to a YSort Node, then add the YSort Node and all it's children (sortable objects) as a child to the TileMap node. May need some other gdscript with it but im not sure. I think it works out of the box like that, if you check out the Isometric example or other iso demos people have made they make use of it, it's so movable objects can sort at runtime I believe.

**Comment by rvcalisto** [comment]
No problem! Now, to follow the path really depends on what you want to do and how your project works. But I'd gamble on your later suggestion, as it makes the functions individual and avoids possible access conflicts with multiple instances. 

That whole '_input' function on nav was only to show how you could go about triggering and modifying pathfinder related stuff. The important thing is that every pathfinder has to use data from the same 'nav.gd' script, so they all can work with the same information and changes.

And thank you for the heads up. I completely missed that YSort Node!
