### ISSUE TITLE
godot 3

### ISSUE THREAD

**Issue by ttux** [Lohan120/GodotIsoPathfinder#2]
This is not a question but a request for help. I am trying to use your custom path finder in a godot 3 project without success. I think there is something I am missing in what you've done. So I tried to create a new project in godot3 replicating yours but it's not working. I would love if you could take a look in case you can quickly see what I have missed. Project is at https://github.com/ttux/GodotIsoCustomPathfinder3

**Comment by rvcalisto** [comment]
Looked at your project. Thing is that in Godot 3.0, arrays are by default references, if you define an array like `Array()` inside a function that gets called multiple times or in an iteration, it doesn't reset the array like in 2.1.4. This made some problems in the _pathfinder.gd_

Also, in the _draw.gd_, you didn't initialized the fixed frame process. In 3.0 it is now called `_physics_process` to avoid confusion. So the changes are:

**[drawn.gd]**
Rename _fixed_process(delta) to: 
`_physics_process(delta)` @ line 21
Initialize the physics_process in the _ready() by putting:
`set_physics_process(true)` @ line 20


**[pathfinder.gd]**
Declare an empty array by replacing `Array()` for `[]` @ line 36
Declare an empty array by replacing `Array()` for `[]` @ line 143


And that's it.

**Comment by ttux** [comment]
Ah ah, I just found that out and saw your comment now... I created an issue on godot github already https://github.com/godotengine/godot/issues/13157

I updated the project to use priority = [] instead

I'll close the issue I created as I guess this is an expected/wanted behavior in godot 3.

Thanks a lot for your work by the way, I managed to get things working in my project which is structured differently and with multiple TileMap.

Do you want to create a branch in your project for godot3 then I can delete https://github.com/ttux/GodotIsoCustomPathfinder3

**Comment by rvcalisto** [comment]
Cool. Yes, I was waiting until the first 3.0 demo to do it but I guess I'll push it now, for consistency.
